Book model
wolox-training/glg-java pull request #3
Opened 2019-12-06 15:49 UTC by wleoguty91

## Summary

- Added book model

## Trello Card

- https://trello.com/c/2nKdmq4F/14-crear-modelo-de-book

![Screenshot from 2019-12-06 12-47-23](https://user-images.githubusercontent.com/42581484/70335812-c91a7680-1826-11ea-87eb-6e56f4c69fef.png)

2019-12-09 13:58 UTC, facucompe requested changes
Check the database to see if JPA is mapping the model correctly

2019-12-09 13:58 UTC, facucompe commented on src/main/java/wolox/training/models/Book.java
> +
Missing
```
@Entity
@Table(name="book")
```

2019-12-09 13:58 UTC, facucompe commented on src/main/java/wolox/training/models/Book.java
> +    @Column()
I think you can remove those parentheses

2019-12-09 13:58 UTC, facucompe commented on src/main/java/wolox/training/models/Book.java
> +    public Book(String author, String image, String title, String subtitle,
You need to add a constructor with no args too. JPA use it to create the instance object.

2019-12-09 13:58 UTC, facucompe commented on src/main/java/wolox/training/models/Book.java
> +    public String getGenre() {
I recommend using [lombok](https://projectlombok.org/setup/gradle) to implement getters and setters

2019-12-10 22:30 UTC, leonplondon commented on src/main/java/wolox/training/models/Book.java
> +
Also add appropriate indentation

2019-12-11 14:15 UTC, facucompe approved these changes

2019-12-11 23:20 UTC, leonplondon approved these changes

2019-12-12 14:52 UTC, merged